### ISSUE TITLE
Mask list out of range when symmetry >1 in combine psf function

### ISSUE THREAD

**Issue by LyneVdV** [sibirrer/psfr#8] opened 2022-12-07 16:21 UTC
* psfr version: latest
* Python version: 3.8
* Operating System: Linux

### Description
In the combine_psf function, around lines 633-647, is the following code:
```
  i = 0
    for j, kernel_new in enumerate(kernel_list_new):
        if mask_list is None:
            mask = 1
        else:
            mask = mask_list[i]

        for k in range(symmetry):
            kernel_rotated = image_util.rotateImage(kernel_new, angle * k)
            kernel_norm = kernel_util.kernel_norm(kernel_rotated)
            kernel_list[i, :, :] = kernel_norm
            # weight according to surface brightness, inverse variance map, and mask
            error_map_list[j][error_map_list[j] < 10 ** (-10)] = 10 ** (-10)
            weights[i, :, :] = amplitude_list[j] * 1 / error_map_list[j] * mask
            i += 1

```
The function iterates on the kernel_list_new and, inside, on symmetry. However, as` i `is incremented with symmetry , the `mask_list[i]` goes out of range. Maybe using `mask_list[j]` would be more appropriate ?

On a related note, I am not 100% sure I undersand the weighting but if it is indeed a weight map and not just a scalar, should the mask (and maybe amplitude and error map) also be rotated before entering the weighting ?

**Comment by sibirrer** [comment] 2022-12-07 18:28
Thank you very much @LyneVdV ! Indeed the i -> j is a bug and the rotation of the mask and error_map was not kept track with symmetries. I think I fixed it with the latest commit but ping me if you still have issues (or make a pull request yourself)., or otherwise close the issue.

**Comment by LyneVdV** [comment] 2022-12-08 10:36
Thank you @sibirrer ! This part is well fixed !
However, when the 'median_weight' stacking option is used with symmetry >1, there is another issue:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-24-0415ce8b606c> in <module>
----> 1 psf_psfrF160W, center_list_psfrF160W, mask_listF160W = stack_psf(list_star_all[0], oversampling=oversampling, 
      2                                                   saturation_limit=None, num_iteration=20,
      3                                                   n_recenter=5,error_map_list=list_noise_all[0],
      4                                                   kwargs_one_step={'step_factor':0.2, 'deshift_order':3},
      5                                                   kwargs_psf_stacking={'stacking_option':'median_weight','symmetry':4},

~/miniconda3/envs/lenstro1.11.0/lib/python3.8/site-packages/psfr/psfr/psfr.py in stack_psf(star_list, oversampling, mask_list, error_map_list, saturation_limit, num_iteration, n_recenter, verbose, kwargs_one_step, psf_initial_guess, kwargs_psf_stacking, centroid_optimizer, **kwargs_animate)
    111         mask_list_one_step = None
    112     for j in range(num_iteration):
--> 113         psf_guess = one_step_psf_estimate(star_list, psf_guess, center_list, mask_list_one_step,
    114                                           error_map_list=error_map_list, oversampling=oversampling,
    115                                           **kwargs_psf_stacking, **kwargs_one_step)

~/miniconda3/envs/lenstro1.11.0/lib/python3.8/site-packages/psfr/psfr/psfr.py in one_step_psf_estimate(star_list, psf_guess, center_list, mask_list, error_map_list, oversampling, step_factor, oversampled_residual_deshifting, deshift_order, verbose, **kwargs_psf_stacking)
    294 
    295     # TODO: None as input for mask_list if mask are irrelevant
--> 296     kernel_new = combine_psf(psf_list_new, psf_guess, factor=step_factor, mask_list=mask_list_oversampled,
    297                              amplitude_list=amplitude_list, error_map_list=error_map_list_psf,
    298                              **psf_stacking_options)

~/miniconda3/envs/lenstro1.11.0/lib/python3.8/site-packages/psfr/psfr/psfr.py in combine_psf(kernel_list_new, kernel_old, mask_list, amplitude_list, factor, stacking_option, symmetry, combine_with_old, error_map_list)
    670             cutoff = np.sum(flattened_weights[:, i]) / 2.0  # weights
    671             pixels = np.sort(pixels)
--> 672             median = pixels[cumsum >= cutoff][0]
    673             new_img.append(median)
    674         kernel_new = np.array(new_img).reshape(x_dim, y_dim)

IndexError: index 0 is out of bounds for axis 0 with size 0


```
I am not sure to know where it is coming from. I don't have the issue when` symmetry=1`.  I don't see why the cumulative sum would never be above or equal to the sum / 2. ...

**Comment by sibirrer** [comment] 2022-12-08 19:37
Hi @LyneVdV , hmm, can you send me an example to reproduce this error? I added a quick test in combine_psf() but could not reproduce it there. Thank you!

**Closed as completed** 2022-12-12 10:04 UTC
